### ISSUE TITLE
Esp8266 port for freertos

### ISSUE THREAD

**Issue by jonsmirl** [loboris/K210_FreeRTOS_SDK#1]
There is an esp8266/lwip port in the STM AVS package

https://www.st.com/en/embedded-software/x-cube-vs4a.html

./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/Config
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/Config/jansson_config.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_wifi_private.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/network.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_network.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_lwip_porting_imp.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_network_private.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_lwip_drv_network.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_lwip_network_imp.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_lwip_net_sockets.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvOS.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvGlueAvs.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvCore.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvProtocol.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvCore.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvOS.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvEvents.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvComUart.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvGlueAvs.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espDrv/espDrvNetif.c
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/blank-1.0-0x7E000.bin
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/esp_init_data_default-1.0-0x7C000.bin
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/LICENSE_bin_files.txt
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/flash-espFw.sh
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/flash-espFw.bat
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/licenses.txt
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/espFw.eagle.irom0text-1.0-0x20000.bin
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/STUsbCom.exe
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/esp_tool.exe
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/espFwBin/espFw.eagle.flash-1.0-0x00000.bin
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/threading_alt.h
./Middlewares/ST/STVS4A/Src/Porting/Network/LWIP_esp/avs_lwip_tls_imp.c

**Comment by loboris** [comment]
> There is an esp8266/lwip port in the STM AVS package
> 
I don't see how is this related to this repository.
